root: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: "@babel/eslint-parser"
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
