root: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
